### ISSUE TITLE
PHP malware

### ISSUE THREAD

**Issue by kenorb** [clemenceD/websiteattacked#1]
As you name suggests, your website was attacked:)

There are PHP malware files in your repository in the following locations:
- https://github.com/clemenceD/websiteattacked/blob/backup-2014-11-11/www/wp-content/plugins/sitepress-multilingual-cms/modules/cache-plugins-integration/.functions.php
- https://github.com/clemenceD/websiteattacked/blob/47dbcffc83f97f5bb89fa50cdca39246cba96a85/www/wp-content/plugins/wpml-translation-management/locale/.test.php

So double check if your site is still infected.

See: http://security.stackexchange.com/q/86094/11825

**Comment by clemenceD** [comment]
Thanks for your email ! Much appreciated :) In the meantime, I've switched my website into a static mode to get rid off the issue. 

I'll delete the files from github.

Have a nice day,

**Comment by kenorb** [comment]
You can keep them if you wish, this was just to let you know where are the malware files if you didn't figure it out yet. Removing these files should probably fix the problem, after you would upgrade your Wordpress.
